### ISSUE TITLE
Is there any more info on this?

### ISSUE THREAD

**Issue by denzo** [ember-best-practices/eslint-plugin-ember-best-practices#1]
This looks very appealing as our development team is growing. Is there any more info on how to use it?

**Comment by chadhietala** [comment]
Still a WIP. Hoping to work on this over the next couple months.

**Comment by chadhietala** [comment]
@denzo this now works, but it's going to be an on going thing for a while. Are there rules in particular you are interested in?

**Comment by runspired** [comment]
Closing this since stale.
