### ISSUE TITLE
const { $ } = Ember; still triggers no-global-jquery

### ISSUE THREAD

**Issue by Gaurav0** [ember-best-practices/eslint-plugin-ember-best-practices#47]
Using

```
const { $ } = Ember;
```

does not stop the `no-global-jquery` warning

**Comment by runspired** [comment]
@Gaurav0 because that still counts as using global jQuery.

**Comment by trentmwillis** [comment]
@runspired if that is the case, then the documentation needs to be updated, as it explicitly states:

> Use `Ember.$` instead.

Which is what the above use case is doing.

I'm reopening until the above use case is supported or the documentation is updated.

**Comment by scalvert** [comment]
Agree. We can fix the rule to account for destructuring.
