### ISSUE TITLE
run.once scheduleOnce with anonymous function

### ISSUE THREAD

**Issue by stefanpenner** [ember-best-practices/eslint-plugin-ember-best-practices#57]
Both of the following are wasteful, as the uniqueness `once` offers is based on function uniqueness, and each invocation of these lines will always create a new function instance, resulting in uniqueness checks, that will never be hits.

```js
Ember.run.scheduleOnce('afterRender', () => { })
Ember.run.once(() => { })
```

**Comment by nlfurniss** [comment]
Fixed by #69
