### ISSUE TITLE
no-global-jquery invalidates for locally imported jquery

### ISSUE THREAD

**Issue by pschutz93** [ember-best-practices/eslint-plugin-ember-best-practices#74]
The no-global-jquery rule invalidates if I import jQuery using an ES6 import. 

```
import Ember from 'ember';
import $ from 'jquery';

export default Ember.Component({
  init() {
    this.el = $('.test');
  }
});
```

While this may have been intended, it seems to me that importing jQuery using `import` should be considered a _best practice_ given that `ember-cli-shims` [supports](https://github.com/ember-cli/ember-cli-shims/blob/master/vendor/ember-cli-shims/app-shims.js#L285) the importing of jQuery in such a manner and that seems to be the direction Ember is heading in. I would be happy to put together a pull request addressing this but wanted to see if this behavior is intentional or simply an oversight.

**Comment by kratiahuja** [comment]
I don't think you should be using jQuery using `import` since that will most likely fail in server side rendering when access the jQuery API.

**Comment by pschutz93** [comment]
I agree that one must be careful with where jQuery is used to make sure server side rendering is not broken. However, how is using `import` with jQuery any worse than accessing it via `Ember.$`?

**Comment by kratiahuja** [comment]
It's not any worse. I think we already have linters around `Ember.$`. However, if I remember correctly `Ember.$` will always be the packaged jQuery version that you are recommended to use v/s global jQuery could be override.
