### ISSUE TITLE
Compatibility with JavaScript Modules API (RFC 176)

### ISSUE THREAD

**Issue by shamcode** [ember-best-practices/eslint-plugin-ember-best-practices#77]
Hi! My code use [JavaScript Modules API](https://github.com/emberjs/rfcs/pull/176).
Sample code:
```
import EmberObject from '@ember/object';
```
And then I try to run tests with `eslint-plugin-ember-best-practices`, I get an exception:
```
TypeError: Cannot read property 'name' of undefined
```
[First line from stack trace](https://github.com/ember-best-practices/eslint-plugin-ember-best-practices/blob/master/lib/utils/imports.js#L10)

**Comment by trentmwillis** [comment]
Would you mind opening a PR to fix this issue? Or at least a reproduction would be helpful.
